version: '2'

services:

  master:
    container_name: ros_master
    build: 
        context: ros/.
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    command: 
        - roscore

  arduino:
    container_name: rosnode_arduino
    build:
        context: docker-arduino/.
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    devices:
        - "/dev/ttyACM0:/dev/ttyACM0"
    depends_on:
        - "master"
    environment:
        - "ROS_HOSTNAME=arduino"
        - "ROS_MASTER_URI=http://master:11311"
    command: rosrun rosserial_python serial_node.py /dev/ttyACM0 _baud:=115200
